# Generated by Django 3.2.3 on 2021-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='media/none.jpg', upload_to='media/files/'),
        ),
    ]
