# Generated by Django 3.2.3 on 2021-05-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
    ]
