# Generated by Django 3.2.3 on 2021-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_text_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='media/none.jpg', upload_to='files/'),
        ),
    ]
