# Generated by Django 3.2.3 on 2021-05-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_imagae',
            new_name='profile_image',
        ),
    ]
