# Generated by Django 3.2.3 on 2021-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
