# Generated by Django 3.2.3 on 2021-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210531_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_body',
            field=models.CharField(default='none', max_length=90),
        ),
    ]
