# Generated by Django 3.2.3 on 2021-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_body_sys',
            field=models.TextField(default=''),
        ),
    ]
