# Generated by Django 3.2.3 on 2021-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='file',
        ),
        migrations.AddField(
            model_name='postfile',
            name='image',
            field=models.ImageField(blank=True, default='none.jpg', upload_to=''),
        ),
    ]
