# Generated by Django 3.2.3 on 2021-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210628_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
