# Generated by Django 3.2.3 on 2021-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_is_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_auth',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
