# Generated by Django 3.2.3 on 2021-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210702_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
